[options]
Architecture = auto
NoExtract = share/* *.exe
SigLevel = Never
DisableDownloadTimeout

[msys-cross]
Server = file:///repo
SigLevel = Never

[mingw64]
Server = https://repo.msys2.org/mingw/mingw64/
SigLevel = Never

[mingw32]
Server = https://repo.msys2.org/mingw/mingw32/
SigLevel = Never

[ucrt64]
Server = https://repo.msys2.org/mingw/ucrt64/
SigLevel = Never

[msys]
Server = https://repo.msys2.org/msys/x86_64/
SigLevel = Never
