#!/bin/bash
# Build the msys2-cross toolchain packages for HOST = arm64 macOS 11.0
# (self-contained arm64 Mach-O), TARGETS = mingw32/mingw64/ucrt64/cygwin, on a Linux
# x86_64 build machine using zig cc. Output: a SEPARATE pacman repo under repo-darwin/.
#
#   bash scripts/build-darwin.sh
#
# Fully independent of the linux build (scripts/build.sh): the GCC Canadian-cross
# `specs`/`self-test` passes (which run the unrunnable arm64 host xgcc) are satisfied by
# wine specs-helpers wrapping the MSYS2-native gcc.exe in the build sysroot (generated by
# prepare-build-sysroot.sh). So this can run as a parallel CI job.
set -euo pipefail

SCRIPTS_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPTS_DIR/.." && pwd)"

# zig target = arm64 macOS 11.0. Drives the zigcc wrapper target, the per-target deps
# prefix, and (via the conf) CARCH/CHOST. Exported in THIS shell because build_deps.sh
# and setup_zig_env read it directly (outside makepkg, the darwin conf doesn't reach them).
export ZIG_TARGET="aarch64-macos.11.0"

# Paths — darwin uses its OWN repo (repo-darwin/) and per-target deps prefix so it never
# collides with a linux build sharing the same checkout.
export PKGDEST="${PKGDEST:-$PROJECT_ROOT/repo-darwin}"
export SRCDEST="${SRCDEST:-$PROJECT_ROOT/build/sources}"
export LOGDEST="${LOGDEST:-$PROJECT_ROOT/build/logs}"
export DEPS_INSTALL="${DEPS_INSTALL:-$PROJECT_ROOT/deps/install-$ZIG_TARGET}"
export DEPS="${DEPS:-$DEPS_INSTALL}"
export BOOTSTRAP_PREFIX="${BOOTSTRAP_PREFIX:-$PROJECT_ROOT/build/bootstrap-prefix}"
export INSTALL_PREFIX="${INSTALL_PREFIX:-$PROJECT_ROOT/build/install-prefix-darwin}"
export ZIG_PATH="${ZIG_PATH:-$PROJECT_ROOT/build/zig}"
export DEPS_CACHE="$PROJECT_ROOT/deps"
export JOBS="${JOBS:-$(nproc)}"

# Cross-build knobs (read by the PKGBUILDs; the conf also sets ZIG_TARGET/_MSYS_CROSS_HOST
# inside makepkg, but build_deps.sh — invoked here directly — needs _MSYS_CROSS_HOST too).
export _MSYS_CROSS_HOST="aarch64-apple-darwin20"
export _MSYS_CROSS_DUMPSPECS=1
# Forward the darwin makepkg config to build_pkg (both the --packagelist dry-run and the
# real build) so CARCH=arm64/PKGEXT=.zst are in effect and skip-detection names match.
export _MSYS_CROSS_MAKEPKG_CONFIG="$SCRIPTS_DIR/makepkg-darwin-arm64.conf"

mkdir -p "$PKGDEST" "$SRCDEST" "$LOGDEST" "$DEPS_INSTALL" "$INSTALL_PREFIX" "$PROJECT_ROOT/build"

echo "=== msys2-cross DARWIN build (host=arm64 macOS 11.0) ==="
echo "PKGDEST:    $PKGDEST"
echo "DEPS:       $DEPS"
echo "ZIG_TARGET: $ZIG_TARGET"
df -h "$PROJECT_ROOT" | tail -1
echo

export PATH="$INSTALL_PREFIX/bin:$PATH"

# ---- Step 0: host build tools (+ wine for the specs-helpers, llvm for build_deps NM) ----
echo "=== Installing host build tools ==="
pacman -Syu --noconfirm --noprogressbar 2>&1 | tail -2
pacman -S --noconfirm --noprogressbar --needed base-devel curl git zstd sudo llvm wine 2>&1 | tail -2

if ! id builduser >/dev/null 2>&1; then
    useradd -m builduser
    echo "builduser ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers
fi
echo

# Shared helpers (run_as_builduser / build_pkg / install_local).
source "$SCRIPTS_DIR/build-common.sh"

# ---- Step 1: zig ----
echo "===== Step 1: Prepare Zig ====="
bash "$SCRIPTS_DIR/prepare-zig.sh"

# ---- Step 2: build sysroots + wine specs-helpers ----
# prepare-build-sysroot.sh installs the MSYS2 target sysroots (which include the native
# gcc.exe per target) AND generates the wine specs-helpers into
# $BOOTSTRAP_PREFIX/specs-helper/bin (used as GCC_FOR_TARGET by the GCC PKGBUILDs).
echo ""
echo "===== Step 2: Prepare build sysroots + wine specs-helpers ====="
bash "$SCRIPTS_DIR/prepare-build-sysroot.sh"
# The wineprefix under specs-helper/ is created as root here; chown so builduser can use it.
chown -R builduser:builduser "$BOOTSTRAP_PREFIX/specs-helper" 2>/dev/null || true

# ---- Step 3: arm64 static deps (gmp/mpfr/mpc/isl/zlib/zstd as Mach-O .a) ----
echo ""
echo "===== Step 3: Build static dependencies (arm64 Mach-O) ====="
run_as_builduser bash "$SCRIPTS_DIR/build_deps.sh"

# ---- Step 4: build packages (binutils then gcc) per target ----
echo ""
echo "===== Step 4: Build darwin packages ====="
# binutils handles all four targets via _MSYS_CROSS_TARGET (incl. cygwin). It needs no
# specs-helper. Order it before gcc (mirrors the linux build).
for _t in mingw64 mingw32 ucrt64 cygwin; do
    export _MSYS_CROSS_TARGET="$_t"
    build_pkg "msys-cross-binutils" "-fCd --skippgpcheck --nocheck --ignorearch"
done
unset _MSYS_CROSS_TARGET

# gcc: mingw64/32/ucrt64 via the msys-cross-gcc PKGBUILD's _MSYS_CROSS_TARGET; the GCC
# specs/self-test use the wine specs-helper. (gcc's configure probes target as/ld but
# all-gcc never executes them — it only builds the host compiler — so a missing
# build-runnable target as/ld is harmless.)
for _t in mingw64 mingw32 ucrt64; do
    export _MSYS_CROSS_TARGET="$_t"
    build_pkg "msys-cross-gcc" "-fCd --skippgpcheck --nocheck --ignorearch"
done
unset _MSYS_CROSS_TARGET

# cygwin gcc is a separate PKGBUILD (fixed triple x86_64-pc-cygwin).
build_pkg "msys-cross-cygwin-gcc" "-fCd --skippgpcheck --nocheck --ignorearch"

# ---- Step 5: darwin repo database (SEPARATE from the linux msys-cross.db) ----
echo ""
echo "===== Step 5: Darwin repo database ====="
rm -f "$PKGDEST"/msys-cross-darwin.db* "$PKGDEST"/msys-cross-darwin.files*
shopt -s nullglob
for pkg in "$PKGDEST"/*.pkg.tar.*; do
    repo-add "$PKGDEST/msys-cross-darwin.db.tar.gz" "$pkg"
done
shopt -u nullglob

echo ""
echo "===== Darwin build complete ====="
echo "Repo: $PKGDEST"
ls "$PKGDEST"/*.pkg.tar.* 2>/dev/null | while read -r f; do echo "  $(basename "$f")"; done
df -h "$PROJECT_ROOT" | tail -1
