#!/bin/bash
# Build all msys2-cross toolchain packages from scratch.
#
#   bash scripts/build.sh            # HOST = build = x86_64 Linux (default)
#   bash scripts/build.sh darwin     # HOST = arm64 macOS 11.0 (cross from Linux)
#
# One entrypoint, two targets. The shared body (Steps 0-6) is identical; all
# per-target divergence is pulled up into the `case $TARGET` config block below.
#
# Linux:  TARGETS = mingw32/mingw64/ucrt64/cygwin, output repo under repo/.
# Darwin: HOST is a self-contained arm64 Mach-O (cross-built with zig cc); the GCC
#         Canadian-cross specs/self-test passes run the unrunnable arm64 host xgcc
#         via wine specs-helpers (generated by prepare-build-sysroot.sh). Output is
#         a SEPARATE pacman repo under repo-darwin/, so a linux and a darwin build
#         can share the same checkout and run as parallel CI jobs.
#
# Prerequisites: base-devel, curl, git, zstd (installed automatically in container)
# Everything else is downloaded/built inside the container.
set -euo pipefail

TARGET="${1:-linux}"
case "$TARGET" in
    linux|darwin) ;;
    *)
        echo "error: unknown target '$TARGET' (expected: linux | darwin)" >&2
        exit 1
        ;;
esac

# Phase selector — lets CI split the monolithic build across parallel runners while
# keeping `build.sh <target>` (= `all`) working verbatim for local dev / fallback.
#   all (default)        Steps 0-6 in one process (the original behaviour)
#   prep                 Steps 0-3 only (baked into the prep container image)
#   chain:<mingw64|mingw32|ucrt64|cygwin>
#                        foundation installs + binutils-<t> -> install -> gcc-<t>
#                        (cygwin uses msys-cross-cygwin-gcc). Assumes prep already ran.
#   clang                Step 4b only. Assumes prep already ran.
#   assemble             Steps 5-6 (repo-add db + installer) over a populated PKGDEST.
# A chain/clang/assemble phase expects the prep outputs (zig, sysroots, deps) present —
# in CI they come from the prep image; locally, run `build.sh <target> prep` first.
PHASE="${2:-all}"
CHAIN_TARGET=""
case "$PHASE" in
    all|prep|clang|assemble) ;;
    chain:*) CHAIN_TARGET="${PHASE#chain:}"
        case "$CHAIN_TARGET" in
            mingw64|mingw32|ucrt64|cygwin) ;;
            *) echo "error: chain target must be mingw64|mingw32|ucrt64|cygwin (got '$CHAIN_TARGET')" >&2; exit 1 ;;
        esac ;;
    *)
        echo "error: unknown phase '$PHASE' (expected: all | prep | chain:<target> | clang | assemble)" >&2
        exit 1
        ;;
esac

SCRIPTS_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPTS_DIR/.." && pwd)"

# ---- Per-target config ----
# Sets the env file to source, PKGDEST, makepkg knobs, clang gate, db name, and
# (darwin only) the installer overrides. ZIG_TARGET / MSYS_CROSS_HOST /
# MSYS_CROSS_DUMPSPECS come from `source env-$TARGET.sh` — never re-set inline.
case "$TARGET" in
    linux)
        # Per-target cross env (ZIG_TARGET, MSYS_CROSS_HOST/MSYS_CROSS_BUILD, the
        # MSYS_CROSS_ENV_LOADED marker) — single source of truth, shared with the makepkg
        # conf. Sourced first so the marker guard in msys-cross-common.sh / build_deps.sh
        # passes and the consumers can read each var without a baked-in default.
        source "$SCRIPTS_DIR/env-linux.sh"

        export PKGDEST="${PKGDEST:-$PROJECT_ROOT/repo}"
        # MAKEPKG_ARGS empty -> build_pkg's `${2:--fCd --skippgpcheck}` default fires.
        MAKEPKG_ARGS=""
        BUILD_CLANG=true
        DB_NAME="msys-cross"
        ;;
    darwin)
        # Per-target cross env (ZIG_TARGET=arm64 macOS 11.0, MSYS_CROSS_HOST,
        # MSYS_CROSS_DUMPSPECS, the MSYS_CROSS_ENV_LOADED marker) — single source of
        # truth, shared with the makepkg conf. Sourced first because build_deps.sh /
        # setup_zig_env read these directly outside makepkg (the darwin conf doesn't
        # reach them) and the deps path below derives from ZIG_TARGET.
        source "$SCRIPTS_DIR/env-darwin.sh"

        export PKGDEST="${PKGDEST:-$PROJECT_ROOT/repo-darwin}"
        # Forward the darwin makepkg config to build_pkg (both the --packagelist dry-run
        # and the real build) so CARCH=arm64/PKGEXT=.zst are in effect and skip-detection
        # names match.
        export MSYS_CROSS_MAKEPKG_CONFIG="$SCRIPTS_DIR/makepkg-darwin-arm64.conf"
        MAKEPKG_ARGS="-fCd --skippgpcheck --nocheck --ignorearch"
        # INSTALL_ARCH=arm64 (for install_local's host pacman --arch) is exported by
        # env-darwin.sh, sourced above — the single source of truth for per-target env.
        # clang IS built for the darwin host: the same from-source PKGBUILD cross-builds
        # an arm64 Mach-O clang+lld with zig cc (build() branches on ZIG_TARGET for the
        # Darwin host triple / CMAKE_SYSTEM_NAME). Unlike gcc, clang is a single driver,
        # so no Canadian-cross specs dance is needed — it just retargets via zig.
        BUILD_CLANG=true
        DB_NAME="msys-cross-darwin"
        # Installer overrides: darwin pacman.conf (Architecture=arm64, [msys-cross-darwin]
        # -> /repo-darwin) and a darwin-specific output name.
        export INSTALLER_DIR="${INSTALLER_DIR:-$PROJECT_ROOT/installer-darwin}"
        export PACMAN_CONF="$SCRIPTS_DIR/../pkgs/msys-cross-pacman/pacman-darwin.conf"
        export BOOTSTRAP_TARBALL="${BOOTSTRAP_TARBALL:-$PKGDEST/bootstrap-darwin.tar.xz}"
        ;;
esac

# ---- Shared paths — keyed on $ZIG_TARGET so the two targets never collide in one
# checkout. Writable destinations live under build/; deps under deps/. ----
export SRCDEST="${SRCDEST:-$PROJECT_ROOT/build/sources}"
export LOGDEST="${LOGDEST:-$PROJECT_ROOT/build/logs}"
export DEPS_INSTALL="${DEPS_INSTALL:-$PROJECT_ROOT/deps/install-$ZIG_TARGET}"
export DEPS="${DEPS:-$DEPS_INSTALL}"
export BOOTSTRAP_PREFIX="${BOOTSTRAP_PREFIX:-$PROJECT_ROOT/build/bootstrap-prefix}"
export INSTALL_PREFIX="${INSTALL_PREFIX:-$PROJECT_ROOT/build/install-$ZIG_TARGET}"
export ZIG_PATH="${ZIG_PATH:-$PROJECT_ROOT/build/zig}"
export DEPS_CACHE="$PROJECT_ROOT/deps"    # ro mount for cached tarballs
export JOBS="${JOBS:-$(nproc)}"

mkdir -p "$PKGDEST" "$SRCDEST" "$LOGDEST" "$DEPS_INSTALL" "$INSTALL_PREFIX" "$PROJECT_ROOT/build"

echo "=== msys2-cross build (target=$TARGET) ==="
echo "PKGDEST:    $PKGDEST"
echo "BOOTSTRAP:  $BOOTSTRAP_PREFIX"
echo "INSTALL:    $INSTALL_PREFIX"
echo "DEPS:       $DEPS"
echo "ZIG_TARGET: $ZIG_TARGET"
echo "ZIG_PATH:   $ZIG_PATH"
[ "$TARGET" = darwin ] && df -h "$PROJECT_ROOT" | tail -1
echo

# Cross-binutils from install prefix must be in PATH for GCC builds
export PATH="$INSTALL_PREFIX/bin:$PATH"

# Per-phase gates. `all` runs everything; the split phases run only their slice.
_do_prep=false; _do_chain=false; _do_clang=false; _do_assemble=false
case "$PHASE" in
    all)      _do_prep=true; _do_chain=true; _do_clang=true; _do_assemble=true ;;
    prep)     _do_prep=true ;;
    chain:*)  _do_chain=true ;;
    clang)    _do_clang=true ;;
    assemble) _do_assemble=true ;;
esac
# The split phases (chain/clang/assemble) run inside the prep container image, which already
# has the host tools + builduser + zig/sysroots/deps from the `prep` phase. They still need
# the shared helpers and builduser to exist; Step 0 below installs tools only when prepping,
# but always ensures builduser + sources build-common.sh.

# ---- Step 0: Install host build tools (prep only) ----
echo "=== Installing host build tools ==="
if $_do_prep; then
pacman -Syu --noconfirm --noprogressbar 2>&1 | tail -2
# Union host package list for both targets:
# llvm: provides llvm-nm, which build_deps.sh uses as NM for cross targets — the host
# GNU nm can't read a cross object (e.g. arm64 Mach-O), which breaks gmp's configure.
# meson/cmake/gperf: makedeps of the from-source pacman build.
# wine: runs the GCC specs-helpers on the darwin Canadian-cross (harmless on linux).
pacman -S --noconfirm --noprogressbar --needed base-devel curl git zstd sudo llvm meson cmake gperf wine 2>&1 | tail -2
fi  # _do_prep (host tool install)

# Create unprivileged build user (makepkg refuses to run as root). Needed by ALL phases —
# the prep image already has it, but creating-if-absent is idempotent and keeps `all` working.
if ! id builduser >/dev/null 2>&1; then
    useradd -m builduser
    echo "builduser ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers
fi
echo

# Shared build helpers: run_as_builduser, build_pkg, install_local. Needed by every phase.
source "$SCRIPTS_DIR/build-common.sh"

# ---- Step 1: Prepare zig (prep only) ----
if $_do_prep; then
echo "===== Step 1: Prepare Zig ====="
bash "$SCRIPTS_DIR/prepare-zig.sh"

# ---- Step 2: Prepare build sysroots (MSYS2 target headers/libs) ----
# prepare-build-sysroot.sh installs the MSYS2 target sysroots (which include the native
# gcc.exe per target) AND, when wine is present, generates the wine specs-helpers into
# $BOOTSTRAP_PREFIX/specs-helper/bin (used as GCC_FOR_TARGET by the darwin GCC PKGBUILDs).
# Since wine is now in the union host list, specs-helper is created on BOTH targets; the
# darwin GCC build consumes it (MSYS_CROSS_DUMPSPECS=1), linux ignores it (var unset).
echo ""
echo "===== Step 2: Prepare build sysroots ====="
bash "$SCRIPTS_DIR/prepare-build-sysroot.sh"
# The wineprefix under specs-helper/ is created as root; chown so builduser can use it.
# Guarded because it only exists when wine generated it.
if [ -d "$BOOTSTRAP_PREFIX/specs-helper" ]; then
    chown -R builduser:builduser "$BOOTSTRAP_PREFIX/specs-helper" 2>/dev/null || true
fi

# ---- Step 3: Build / provision static deps ----
echo ""
echo "===== Step 3: Build static dependencies ====="
if [ "$TARGET" = darwin ]; then
    # arm64 static deps — STOLEN from Homebrew bottles, not cross-built. gmp/mpfr/mpc/isl
    # don't cross-compile cleanly on zig's macOS SDK (asm/configure host probes); Homebrew
    # already ships correct arm64 Mach-O .a, so build-deps-darwin.sh fetches those
    # (+ zlib/zstd) into deps/install-$ZIG_TARGET with the same layout build_deps.sh
    # produces. Runs as root here (just curl+bsdtar); chown after so builduser can read.
    bash "$SCRIPTS_DIR/build-deps-darwin.sh"
    chown -R builduser:builduser "$DEPS_INSTALL" 2>/dev/null || true
else
    # Built as builduser (see run_as_builduser) so the sccache server is the same uid
    # as the gcc/binutils phase.
    run_as_builduser bash "$SCRIPTS_DIR/build_deps.sh"
fi
fi  # _do_prep (Steps 1-3)

# build_pkg / install_local live in build-common.sh (sourced above, every phase).

# ---- Foundation packages ----
# The few cheap packages binutils/gcc need installed locally (filesystem/ca-certs/pacman/
# pkgconfig). Built+installed for `all` and for EVERY chain cell (each cell has its own
# per-runner INSTALL_PREFIX). Tiny (pacman -Udd of small pkgs), so the per-cell duplication
# is negligible. Also for clang (its build wants pkgconfig wrappers on PATH).
_build_foundation() {
    echo ""
    echo "===== Foundation packages ====="
    build_pkg "msys-cross-filesystem"      "$MAKEPKG_ARGS"
    build_pkg "msys-cross-ca-certificates" "$MAKEPKG_ARGS"
    build_pkg "msys-cross-pacman"          "$MAKEPKG_ARGS"
    install_local "msys-cross-filesystem-*.pkg.tar.*"
    install_local "msys-cross-ca-certificates-*.pkg.tar.*"
    install_local "msys-cross-pacman-*.pkg.tar.*"
    build_pkg "msys-cross-pkgconfig"       "$MAKEPKG_ARGS"
    install_local "msys-cross-pkgconfig-*.pkg.tar.*"
}

# ---- One target's binutils -> gcc chain ----
# gcc-<t> needs ONLY binutils-<t>'s as/ld on PATH (triple-prefixed), so each target's
# binutils->gcc is a self-contained unit: build binutils, install it locally, build gcc.
# No cross-target binutils needed → cells are independent. The cygwin chain uses the
# separate msys-cross-cygwin-gcc PKGBUILD (fixed triple) instead of the looped msys-cross-gcc.
_build_chain() {
    local _t="$1"
    echo ""
    echo "===== Chain: $_t (binutils -> gcc) ====="
    export MSYS_CROSS_TARGET="$_t"
    build_pkg "msys-cross-binutils" "$MAKEPKG_ARGS"
    # binutils-common (the target-independent BFD plugin) is produced ONLY by the mingw64
    # binutils run (see pkgs/msys-cross-binutils/PKGBUILD: pkgname gains binutils-common iff
    # _mct=mingw64). gcc-<t> only needs the triple-prefixed <t>-binutils as/ld on PATH, not
    # the plugin, so non-mingw64 chains don't install it (the file doesn't exist in their
    # PKGDEST). The mingw64 cell's artifact carries binutils-common to the collect job, which
    # repo-adds it into the shared repo so every <t>-binutils's dependency resolves there.
    if [ "$_t" = mingw64 ]; then
        install_local "msys-cross-binutils-common-*.pkg.tar.*"
    fi
    install_local "msys-cross-${_t}-binutils-*.pkg.tar.*"
    if [ "$_t" = cygwin ]; then
        unset MSYS_CROSS_TARGET
        build_pkg "msys-cross-cygwin-gcc" "$MAKEPKG_ARGS"
        install_local "msys-cross-cygwin-gcc-*.pkg.tar.*"
    else
        build_pkg "msys-cross-gcc" "$MAKEPKG_ARGS"
        unset MSYS_CROSS_TARGET
        install_local "msys-cross-${_t}-gcc-*.pkg.tar.*"
    fi
}

# ---- Step 4: Build packages ----
# `all`  -> foundation + all four chains (mingw64 first so binutils-common is produced once).
# chain:<t> -> foundation + that one chain only (a single CI cell).
if $_do_chain; then
    echo ""
    echo "===== Step 4: Build packages ====="
    _build_foundation
    if [ -n "$CHAIN_TARGET" ]; then
        _build_chain "$CHAIN_TARGET"
    else
        for _t in mingw64 mingw32 ucrt64 cygwin; do
            _build_chain "$_t"
        done
    fi
fi

# ---- Step 4b: Clang cross toolchain (both hosts) ----
# clang is a single driver: ONE self-built clang+lld serves every Windows target via
# -target/--sysroot, so one heavy package (msys-cross-clang, binaries off-PATH under
# libexec/) plus thin per-abi wrapper packages (clang64/clangarm64). LLVM is cross-built
# from source with zig cc (the patched zig from Step 1 supplies the old-glibc aligned-new
# fix); the version follows the mingw-w64-llvm submodule. Unlike gcc/binutils there is no
# Canadian-cross specs step — the driver simply retargets — so the SAME PKGBUILD builds it
# for the linux host (x86_64 ELF) and the darwin host (arm64 Mach-O); build() branches on
# ZIG_TARGET. $MAKEPKG_ARGS carries the per-target makepkg flags (darwin: --ignorearch +
# the darwin --config via MSYS_CROSS_MAKEPKG_CONFIG); linux leaves it empty for the default.
if $_do_clang && $BUILD_CLANG; then
    echo ""
    echo "===== Step 4b: Clang cross toolchain ====="
    build_pkg "msys-cross-clang" "$MAKEPKG_ARGS"  # all three split packages (pkgbase=msys-cross-clang)
    install_local "msys-cross-clang-*.pkg.tar.*"
fi

# ---- Step 5-6: Assemble repo + installer (assemble phase) ----
# In the split topology this runs in the per-host collect job over a PKGDEST already
# populated with every cell's *.pkg.tar.* artifacts; for `all` it runs inline as before.
if $_do_assemble; then
    # ---- Step 5: Create repo database ----
    echo ""
    echo "===== Step 5: Repo database ====="
    rm -f "$PKGDEST/$DB_NAME.db" "$PKGDEST/$DB_NAME.db.tar.gz" "$PKGDEST/$DB_NAME.files" "$PKGDEST/$DB_NAME.files.tar.gz"

    shopt -s nullglob
    for pkg in "$PKGDEST"/*.pkg.tar.*; do
        repo-add "$PKGDEST/$DB_NAME.db.tar.gz" "$pkg"
    done
    shopt -u nullglob

    # ---- Step 6: Build installer ----
    # Darwin set INSTALLER_DIR / PACMAN_CONF / BOOTSTRAP_TARBALL in the config block above;
    # linux uses build_installer.sh's defaults (with the linux installer dir below).
    echo ""
    echo "===== Step 6: Build installer ====="
    export INSTALLER_DIR="${INSTALLER_DIR:-$PROJECT_ROOT/installer}"
    bash "$SCRIPTS_DIR/build_installer.sh"
fi

echo ""
echo "===== Build complete (target=$TARGET, phase=$PHASE) ====="
echo "Repo: $PKGDEST"
ls "$PKGDEST"/*.pkg.tar.* 2>/dev/null | while read -r f; do
    echo "  $(basename "$f")"
done
if $_do_assemble; then
    echo ""
    echo "Database:"
    ls -la "$PKGDEST/$DB_NAME.db.tar.gz" 2>/dev/null || echo "  (no db — nothing assembled)"
fi
[ "$TARGET" = darwin ] && df -h "$PROJECT_ROOT" | tail -1
echo "Done."
